### ISSUE TITLE
Great project!

### ISSUE THREAD

**Issue by gelsas** [jonocairns/aubri#82]
I just found your project here on GitHub and I love the idea to have a "Plex" for my audiobooks. 
Can't wait to test it.

**Comment by jonocairns** [comment]
Awesome! Yeah I'm still working out some stuff but keen to get something up and running for people!

**Comment by gelsas** [comment]
Hello,
I know it just has been one month but I wanted to ask when the first release for testing is out.

**Comment by jonocairns** [comment]
hey there! there is a release available on dockerhub but there are a few things you need to sort out to get it working (I'll try writing up some docs for now)

Requirements
- A postgres instance
- An auth0 account with an app created
- Settings the correct variables at runtime for the aubri container

**Comment by jonocairns** [comment]
note: My goal is to be as seamless as installing the docker container but there's a few things I need to iron out before I get there :)

**Comment by jonocairns** [comment]
![image](https://user-images.githubusercontent.com/182836/76248281-e89dc100-62a5-11ea-9417-cf514e20db8b.png)

**Comment by gelsas** [comment]
Thank you for the update! 
Can't wait to test it. Let me know once you need someone to test. 

I do have an question, well maybe an idea.
Do you plan on also supporting to open/read ebooks as well? Or will it be limited to audiobook? 

I am just asking because sometimes I do like to read along while listening to an audiobook and it would be an awesome feature if I could just open the ebook from within the same application.

Hope you don't mind me suggesting something like that.

Best,
gelsas

**Comment by jonocairns** [comment]
> I do have an question, well maybe an idea.
>Do you plan on also supporting to open/read ebooks as well? Or will it be limited to audiobook?

>I am just asking because sometimes I do like to read along while listening to an audiobook and it >would be an awesome feature if I could just open the ebook from within the same application.

That's an awesome idea @gelsas I'll add it to the backlog. Let me know if you get any more, keen to get them all down in the project board!

**Comment by gelsas** [comment]
Thank you. Glad you like the idea. 

Where is the metadata for the audiobooks from? 
Do you scrape/get them from audible?

**Comment by jonocairns** [comment]
yeah I scrape from audible - I might need to tweak this a bit though

**Comment by gelsas** [comment]
Hi,

Just checking by just wanted to ask how everything is progressing. 

Can't wait to test your first release!

**Comment by gelsas** [comment]
What is the current progress on your project if I may ask,?
